### ISSUE TITLE
Cannot start midway through stream

### ISSUE THREAD

**Issue by t-mullen** [RationalCoding/media-source-stream#1]
Moving from email:

> I saw your project and I tested the demo https://rationalcoding.github.io/media-source-stream/
>
> It looks great and my question is: 
>
> Is it possible to play (remote stream) from time N ?
>
> Scenario: user1 is publishing his stream via data. 20 seconds later user2 enters. Can he watch user1's stream from seconds=20 (real time)  or must he watch the stream from second 0 ?
>
> regards

**Comment by t-mullen** [comment]
Unfortunately the webm clusters will be missing some important header information in the first cluster, and the header cannot be simply added to a later cluster. I'm still working on this myself.

As an alternative to using this module, you can save each webm cluster from media-stream-recorder as a separate file, then cycle 3 video tags. This is what Nile.js did [here](https://github.com/gitsummore/nile.js/blob/master/client/module/broadcaster.js#L76).

I'm trying to see if it's possible to reconstruct the file so that some clusters can be missed, but no progress yet.

**Comment by t-mullen** [comment]
Strangely enough, dropping the first few clusters works fine when the webm is downloaded, which makes me suspect the issue is related to MSE.

**Comment by t-mullen** [comment]
MSE is actually doing the correct thing and accounting for the gap in timecodes.

All that is required is to set `videoElement.currentTime` to the number of milliseconds between when recording started, and the start of the current cluster (usually a SimpleBlock).

```javascript
var clusters = require('webm-cluster-stream')
var cl = clusters()

var t0 = performance.now()
cl.once('data', function (header) {
  // the header can NEVER be skipped
  mediaSource.write(header) // always write the header FIRST
  cl.on('data', function (cluster) {
    // skip several clusters
    if (i++ < 30) {
      // these clusters will not be sent to receiver (start gap)
    } else if (i === 30) {
      var timeOffset = performance.now() - t0
      sourceStream.write(cluster)
      video.currentTime = timeOffset // set currentTime on first cluster 
      video.src = window.URL.createObjectURL(sourceStream.mediaSource)
    } else {
      sourceStream.write(cluster)
    }
  })
})

recordStream.pipe(cl)
```

Parsing the clusters to get the true duration is better, but a slight overestimation works fine as well.

**Comment by RationalCoding** [comment]
I'll probably write another module to handle the timing and simplify things a bit.
