### ISSUE TITLE
trying to stream source via socket

### ISSUE THREAD

**Issue by shakidev** [RationalCoding/media-source-stream#2]
//Server
server.js
    socket.on('stream-video', function (stream) {
        var recordStream = recorder(stream, {
            mimeType: 'video/webm; codecs=vp8',
            interval: 100
        });
        var sourceStream = sourcer();
        recordStream.pipe(sourceStream);
        socket.broadcast.emit("stream-video", sourceStream);
    });

//Streamer

streamer.js 
                    signaling_socket.emit("stream-video", stream);

// Viewers

viewer.js 
signaling_socket.on('stream-video', function(stream){
                var url = window.URL.createObjectURL(stream.mediaSource);
                document.querySelector('video').src = url;
            });

Can I do something like this?

i have error in server side
node_modules/media-recorder-stream/index.js:36
  rs.recorder = new window.MediaRecorder(media, opts)
                    ^

**Comment by t-mullen** [comment]
Just to be clear, you're trying to stream from a browser to a Node server via socket.io?

**Comment by shakidev** [comment]
Yes, I want to make stream from server. 1 streamer -> server -> many viewers
Am I in the right directions moving?

**Comment by t-mullen** [comment]
Ok I understand. So Node has no MediaRecorder API, which is why you're getting that error. You need to do the recording on the streamer's browser. You also need to send the data that the stream emits, not the stream object itself:

server.js
```javascript
socket.on('stream-video', function (data) {
  socket.broadcast.emit("stream-video", data);
})
```

streamer.js
```javascript
var recordStream = recorder(stream, {
  mimeType: 'video/webm; codecs=vp8',
  interval: 100
})
recordStream.on('data', function (data) {
  signaling_socket.emit("stream-video", data);
})
```

viewer.js
```javascript
var sourceStream = MediaSourceStream({  
  mimeType: 'video/webm; codecs="vp8"'
 }) 
var url = window.URL.createObjectURL(sourceStream.mediaSource)
document.querySelector('video').src = url
signaling_socket.on('stream-video', function(data){
  sourceStream.write(data)
})
```

This should work if I haven't missed anything. 

Please note you'll encounter #1 if any clients connect after the stream has already started. Streams can't be played from partway through yet.

**Comment by shakidev** [comment]
> Please note you'll encounter #1 if any clients connect after the stream has already started. Streams can't be played from partway through yet.
Ok.

Uncaught TypeError: Cannot set property 'src' of null
maybe inside stream-video in viewer?

**Comment by t-mullen** [comment]
Did you create a video element? The source I posted isn't nearly complete.

**Comment by shakidev** [comment]
oh,sorry, i created then works fine but have errors
 TypeError: Invalid non-string/buffer chunk  -- media-source-stream.js:1779

**Comment by t-mullen** [comment]
socket.io might be transforming your data when it sends it. Could you log `data` just before `sourceStream.write(data)`?

**Comment by shakidev** [comment]
Object
data:
(28244) [65, 134, 129, 19, 116, 128, 251, 131, 127, 128, 90, 131, 238, 75, 156, 171, 56, 134, 217, 20, 222, 180, 184, 245, 55, 90, 193, 15, 68, 44, 80, 145, 60, 135, 244, 149, 65, 121, 163, 213, 190, 225, 134, 250, 229, 73, 132, 129, 41, 34, 34, 110, 230, 229, 224, 36, 147, 40, 55, 173, 3, 164, 123, 226, 154, 111, 36, 49, 61, 117, 204, 176, 13, 89, 22, 20, 74, 28, 175, 198, 167, 200, 24, 64, 155, 175, 135, 187, 11, 93, 80, 101, 0, 216, 187, 26, 118, 168, 106, 11, …]
type:"Buffer"

**Comment by t-mullen** [comment]
Ah, socket.io wraps everything in an object.

Change:
`sourceStream.write(data)`
to
`sourceStream.write(data.data)`

**Comment by shakidev** [comment]
same error :)
 Uncaught TypeError: Invalid non-string/buffer chunk   -- media-source-stream.js:4482
    at validChunk (media-source-stream.js:1779)
    at MediaSourceStream.Writable.write (

**Comment by shakidev** [comment]
i wanna try at latest version of socket

**Comment by shakidev** [comment]
Are you worked via socket?
I see that you have been doing streaming for a long time) I want to do relaying(restream) through the server, what options can I still use?

**Comment by shakidev** [comment]
I see that you have been doing streaming for a long time) I want to do relaying(restream) through the server, what options can I still use?

**Comment by t-mullen** [comment]
socket.io is converting the Buffer into an Array. You'll have to convert it back with `safe-buffer`.

```javascript
var Buffer = require('safe-buffer').Buffer
sourceStream.write(new Buffer(data.data)) // might be just new Buffer(data), try both
```

**Comment by t-mullen** [comment]
There's really not many options for pure-Node.js streaming right now. There's quite a few decent media servers if you want to take the time to set them up.

**Comment by shakidev** [comment]
Maybe just serialize data?

**Comment by t-mullen** [comment]
If you're going to do your own serialization, I would recommend not using socket.io. It's not designed for binary data anyhow. `simple-websocket` would be better since it deals with Buffer streams to start with.

**Comment by shakidev** [comment]
Nothing happens , blob added, but not playing.

**Comment by t-mullen** [comment]
You cannot add a blob to the stream. It has to be a buffer.

**Comment by t-mullen** [comment]
I'll try to write an example for this on the weekend. It's a common usecase.
